### ISSUE TITLE
Google Font loading

### ISSUE THREAD

**Issue by SahinU88** [dachcom-digital/js-pimcore-formbuilder#11]
I unfortunately don't have any solution yet, but as loading google fonts from the google server without the consent of the user may lead to legal problems in the EU (especially Germany and Austria) we should have an option to add some kind of a consent or a 2nd option to use an alternative service to integrate the recaptcha functionality.

Did you already had a similar situation maybe? I am researching at the moment, and as soon as I have a solution I will comment here.

**Comment by solverat** [comment]
Hey @SahinU88. We're very aware of this problem, but there is actually nothing we can do about it.

Basically, you have three options:
- Don't use the recaptcha extension 
- Before you're going to initialize the recaptcha instance, ask for users permission
- Extend your third party extension (like cookiebot)

**Comment by solverat** [comment]
@SahinU88 Maybe relevant: https://fonts.googleblog.com/2022/11/your-privacy-and-google-fonts.html

**Comment by SahinU88** [comment]
thanks for the further information!
