### ISSUE TITLE
[BUG] Is invalid class being added when visibility changes

### ISSUE THREAD

**Issue by JoeyNtriga** [dachcom-digital/js-pimcore-formbuilder#20]
Hi,

On this page, we have a form that uses the built-in conditional logic to show/hide two input fields.
The two fields should be required when they are visible, so I add validation based on if they are visible or not.
The problem we are facing is when the fields become visible (they are hidden by default), the class is-invalid automatically gets added to the fields resulting in the fields looking like they were incorrectly submitted while this isn't the case.

The project is using pimcore version 10.6.3 and formbuilder version 4.5.0 with js-pimcore-formbuilder version 1.0.8.

Did we set it up wrong, or is this a bug?

Here is what's happening:

https://github.com/dachcom-digital/js-pimcore-formbuilder/assets/130968595/72c63034-f918-4a29-8c5f-34277f1292e6

<img width="1166" alt="270966132-b249cb36-150b-495f-817c-1708f23ddcf2" src="https://github.com/dachcom-digital/js-pimcore-formbuilder/assets/130968595/a2389b61-5104-45e9-8c79-16d7ed950293">

<img width="804" alt="270966145-dfdcbaeb-0949-44f6-b6d6-4c360f30163c" src="https://github.com/dachcom-digital/js-pimcore-formbuilder/assets/130968595/a3aa1b51-84aa-4319-b7c6-812cea0117a0">

Thanks in advance!

**Comment by pascalmoser** [comment]
Hi, thank you for the detailed description.
Yes, the class `is-invalid` should only be set if the form has already been submitted.
