### ISSUE TITLE
ReCaptcha token assignment not working

### ISSUE THREAD

**Issue by patric-eberle** [dachcom-digital/js-pimcore-formbuilder#5]
When the ReCaptcha token from the Google API is returned, the token value is not forwarded to the assignment method.

https://github.com/dachcom-digital/js-pimcore-formbuilder/blob/0d142abb4371913bf29f0cdf103f24ab238c9d0e/src/js/components/recaptchaV3.js#L71

This results in an invalid form submit, returning an error that `We're sorry, but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.`.

I prepared a PR: #4

**Comment by solverat** [comment]
Fixed via #4. Thank yuo @patric-eberle!
