### ISSUE TITLE
Options are shared between instances

### ISSUE THREAD

**Issue by patric-eberle** [dachcom-digital/js-pimcore-formbuilder#8]
When creating a new `FetchManager` instance, it's options are shared between all forms on the page (later forms overwrite previous ones). This happens because `Object.assign(target, ...sources)` does not create a new object but extends the existing default value object.

https://github.com/dachcom-digital/js-pimcore-formbuilder/blob/0d142abb4371913bf29f0cdf103f24ab238c9d0e/src/js/core/fetchManager.js#L11

Pull request: #7

**Comment by solverat** [comment]
Fixed via #7. Thanks again!
